---
- hosts: localhost
  connection: local
  tasks:
  - name: install mysql
    apt:
      name: "{{ item }}"
      state: installed
    with_items:
    - mysql-server
  
  - name: start mysql
    service: name=mysql state=started enabled=true